name: facturasya
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-322.0.dev <4.0.0'

dependencies:
  bounce: ^1.0.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.1.6
  qr_flutter: ^4.1.0
  roulette: ^0.1.5
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
